package com.example.shoppingcartproject.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonTypeId;
import jakarta.persistence.*;

import com.example.shoppingcartproject.model.UserRole;

/**
 * User Model
 * User mode class defines the basic information of a user and stores it in the database.
 * @version 1.0
 * @since 2025-05-18
 */

@Entity
public class User {

    // User ID: Auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    // Email: Email is the primary account, required and unique
    @Column(unique = true, nullable = false)
    private String email;

    // Phone Number is optional, can be used for login
    @Column(unique = true)
    private String phoneNumber;

    // Password: Use @JsonIgnore to hide password in API responses
    @JsonIgnore
    private String password;

    // User Role: Uses th UserRole enum to distinguish roles
    @Enumerated(EnumType.STRING)
    private UserRole role;

    /**
     * Default constructor
     */
    public User() {}

    /**
     * Parameterized constructor
     * @param email
     * @param phoneNumber
     * @param password
     * @param role
     */
    public User(String email, String phoneNumber, String password, UserRole role) {
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.password = password;
        this.role = role;
    }

    // Getters and Setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public UserRole getRole() {
        return role;
    }

    public void setRole(UserRole role) {
        this.role = role;
    }

}
